// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogen-go/ent2ogen/internal/test/ent/predicate"
	"github.com/ogen-go/ent2ogen/internal/test/ent/schemaa"
)

// SchemaADelete is the builder for deleting a SchemaA entity.
type SchemaADelete struct {
	config
	hooks    []Hook
	mutation *SchemaAMutation
}

// Where appends a list predicates to the SchemaADelete builder.
func (sa *SchemaADelete) Where(ps ...predicate.SchemaA) *SchemaADelete {
	sa.mutation.Where(ps...)
	return sa
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sa *SchemaADelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sa.hooks) == 0 {
		affected, err = sa.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SchemaAMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sa.mutation = mutation
			affected, err = sa.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sa.hooks) - 1; i >= 0; i-- {
			if sa.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sa.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sa.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sa *SchemaADelete) ExecX(ctx context.Context) int {
	n, err := sa.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sa *SchemaADelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: schemaa.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: schemaa.FieldID,
			},
		},
	}
	if ps := sa.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sa.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// SchemaADeleteOne is the builder for deleting a single SchemaA entity.
type SchemaADeleteOne struct {
	sa *SchemaADelete
}

// Exec executes the deletion query.
func (sao *SchemaADeleteOne) Exec(ctx context.Context) error {
	n, err := sao.sa.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{schemaa.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sao *SchemaADeleteOne) ExecX(ctx context.Context) {
	sao.sa.ExecX(ctx)
}
