// Code generated by ent, DO NOT EDIT.

package keycapmodel

import (
	"fmt"
)

const (
	// Label holds the string label denoting the keycapmodel type in the database.
	Label = "keycap_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProfile holds the string denoting the profile field in the database.
	FieldProfile = "profile"
	// FieldMaterial holds the string denoting the material field in the database.
	FieldMaterial = "material"
	// Table holds the table name of the keycapmodel in the database.
	Table = "keycap_models"
)

// Columns holds all SQL columns for keycapmodel fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldProfile,
	FieldMaterial,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// Material defines the type for the "material" enum field.
type Material string

// Material values.
const (
	MaterialABS Material = "ABS"
	MaterialPBT Material = "PBT"
)

func (m Material) String() string {
	return string(m)
}

// MaterialValidator is a validator for the "material" field enum values. It is called by the builders before save.
func MaterialValidator(m Material) error {
	switch m {
	case MaterialABS, MaterialPBT:
		return nil
	default:
		return fmt.Errorf("keycapmodel: invalid enum value for material field: %q", m)
	}
}
