// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// KeyboardsColumns holds the columns for the "keyboards" table.
	KeyboardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "price", Type: field.TypeInt64},
		{Name: "discount", Type: field.TypeInt64, Nullable: true},
		{Name: "keyboard_switches", Type: field.TypeInt64},
		{Name: "keyboard_keycaps", Type: field.TypeInt64},
	}
	// KeyboardsTable holds the schema information for the "keyboards" table.
	KeyboardsTable = &schema.Table{
		Name:       "keyboards",
		Columns:    KeyboardsColumns,
		PrimaryKey: []*schema.Column{KeyboardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "keyboards_switch_models_switches",
				Columns:    []*schema.Column{KeyboardsColumns[4]},
				RefColumns: []*schema.Column{SwitchModelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "keyboards_keycap_models_keycaps",
				Columns:    []*schema.Column{KeyboardsColumns[5]},
				RefColumns: []*schema.Column{KeycapModelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// KeycapModelsColumns holds the columns for the "keycap_models" table.
	KeycapModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "profile", Type: field.TypeString},
		{Name: "material", Type: field.TypeEnum, Enums: []string{"ABS", "PBT"}},
	}
	// KeycapModelsTable holds the schema information for the "keycap_models" table.
	KeycapModelsTable = &schema.Table{
		Name:       "keycap_models",
		Columns:    KeycapModelsColumns,
		PrimaryKey: []*schema.Column{KeycapModelsColumns[0]},
	}
	// SwitchModelsColumns holds the columns for the "switch_models" table.
	SwitchModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "switch_type", Type: field.TypeEnum, Enums: []string{"mechanical", "optical", "electrocapacitive"}},
	}
	// SwitchModelsTable holds the schema information for the "switch_models" table.
	SwitchModelsTable = &schema.Table{
		Name:       "switch_models",
		Columns:    SwitchModelsColumns,
		PrimaryKey: []*schema.Column{SwitchModelsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		KeyboardsTable,
		KeycapModelsTable,
		SwitchModelsTable,
	}
)

func init() {
	KeyboardsTable.ForeignKeys[0].RefTable = SwitchModelsTable
	KeyboardsTable.ForeignKeys[1].RefTable = KeycapModelsTable
}
