// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CitiesColumns holds the columns for the "cities" table.
	CitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "required_enum", Type: field.TypeEnum, Enums: []string{"a", "b"}},
		{Name: "nullable_enum", Type: field.TypeEnum, Nullable: true, Enums: []string{"c", "d"}},
	}
	// CitiesTable holds the schema information for the "cities" table.
	CitiesTable = &schema.Table{
		Name:       "cities",
		Columns:    CitiesColumns,
		PrimaryKey: []*schema.Column{CitiesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "user_name", Type: field.TypeString, Unique: true},
		{Name: "optional_nullable_bool", Type: field.TypeBool, Nullable: true},
		{Name: "user_required_city", Type: field.TypeInt64},
		{Name: "user_optional_city", Type: field.TypeInt64, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_cities_required_city",
				Columns:    []*schema.Column{UsersColumns[5]},
				RefColumns: []*schema.Column{CitiesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "users_cities_optional_city",
				Columns:    []*schema.Column{UsersColumns[6]},
				RefColumns: []*schema.Column{CitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UserFriendListColumns holds the columns for the "user_friend_list" table.
	UserFriendListColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "friend_list_id", Type: field.TypeInt64},
	}
	// UserFriendListTable holds the schema information for the "user_friend_list" table.
	UserFriendListTable = &schema.Table{
		Name:       "user_friend_list",
		Columns:    UserFriendListColumns,
		PrimaryKey: []*schema.Column{UserFriendListColumns[0], UserFriendListColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_friend_list_user_id",
				Columns:    []*schema.Column{UserFriendListColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_friend_list_friend_list_id",
				Columns:    []*schema.Column{UserFriendListColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CitiesTable,
		UsersTable,
		UserFriendListTable,
	}
)

func init() {
	UsersTable.ForeignKeys[0].RefTable = CitiesTable
	UsersTable.ForeignKeys[1].RefTable = CitiesTable
	UserFriendListTable.ForeignKeys[0].RefTable = UsersTable
	UserFriendListTable.ForeignKeys[1].RefTable = UsersTable
}
