// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogen-go/ent2ogen/example/ent/keycapmodel"
	"github.com/ogen-go/ent2ogen/example/ent/predicate"
)

// KeycapModelDelete is the builder for deleting a KeycapModel entity.
type KeycapModelDelete struct {
	config
	hooks    []Hook
	mutation *KeycapModelMutation
}

// Where appends a list predicates to the KeycapModelDelete builder.
func (kmd *KeycapModelDelete) Where(ps ...predicate.KeycapModel) *KeycapModelDelete {
	kmd.mutation.Where(ps...)
	return kmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (kmd *KeycapModelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, KeycapModelMutation](ctx, kmd.sqlExec, kmd.mutation, kmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (kmd *KeycapModelDelete) ExecX(ctx context.Context) int {
	n, err := kmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (kmd *KeycapModelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: keycapmodel.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: keycapmodel.FieldID,
			},
		},
	}
	if ps := kmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, kmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	kmd.mutation.done = true
	return affected, err
}

// KeycapModelDeleteOne is the builder for deleting a single KeycapModel entity.
type KeycapModelDeleteOne struct {
	kmd *KeycapModelDelete
}

// Exec executes the deletion query.
func (kmdo *KeycapModelDeleteOne) Exec(ctx context.Context) error {
	n, err := kmdo.kmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{keycapmodel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (kmdo *KeycapModelDeleteOne) ExecX(ctx context.Context) {
	kmdo.kmd.ExecX(ctx)
}
