// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogen-go/ent2ogen/example/ent/predicate"
	"github.com/ogen-go/ent2ogen/example/ent/switchmodel"
)

// SwitchModelDelete is the builder for deleting a SwitchModel entity.
type SwitchModelDelete struct {
	config
	hooks    []Hook
	mutation *SwitchModelMutation
}

// Where appends a list predicates to the SwitchModelDelete builder.
func (smd *SwitchModelDelete) Where(ps ...predicate.SwitchModel) *SwitchModelDelete {
	smd.mutation.Where(ps...)
	return smd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (smd *SwitchModelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, SwitchModelMutation](ctx, smd.sqlExec, smd.mutation, smd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (smd *SwitchModelDelete) ExecX(ctx context.Context) int {
	n, err := smd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (smd *SwitchModelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(switchmodel.Table, sqlgraph.NewFieldSpec(switchmodel.FieldID, field.TypeInt64))
	if ps := smd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, smd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	smd.mutation.done = true
	return affected, err
}

// SwitchModelDeleteOne is the builder for deleting a single SwitchModel entity.
type SwitchModelDeleteOne struct {
	smd *SwitchModelDelete
}

// Where appends a list predicates to the SwitchModelDelete builder.
func (smdo *SwitchModelDeleteOne) Where(ps ...predicate.SwitchModel) *SwitchModelDeleteOne {
	smdo.smd.mutation.Where(ps...)
	return smdo
}

// Exec executes the deletion query.
func (smdo *SwitchModelDeleteOne) Exec(ctx context.Context) error {
	n, err := smdo.smd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{switchmodel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (smdo *SwitchModelDeleteOne) ExecX(ctx context.Context) {
	if err := smdo.Exec(ctx); err != nil {
		panic(err)
	}
}
