// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/ogen-go/ent2ogen/example/ent/city"
	"github.com/ogen-go/ent2ogen/example/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	// Time when entity was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	// Time when entity was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"user_name,omitempty"`
	// OptionalNullableBool holds the value of the "optional_nullable_bool" field.
	OptionalNullableBool *bool `json:"optional_nullable_bool,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges              UserEdges `json:"edges"`
	user_required_city *uuid.UUID
	user_optional_city *uuid.UUID
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// RequiredCity holds the value of the required_city edge.
	RequiredCity *City `json:"required_city,omitempty"`
	// OptionalCity holds the value of the optional_city edge.
	OptionalCity *City `json:"optional_city,omitempty"`
	// FriendList holds the value of the friend_list edge.
	FriendList []*User `json:"friend_list,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// RequiredCityOrErr returns the RequiredCity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) RequiredCityOrErr() (*City, error) {
	if e.loadedTypes[0] {
		if e.RequiredCity == nil {
			// The edge required_city was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: city.Label}
		}
		return e.RequiredCity, nil
	}
	return nil, &NotLoadedError{edge: "required_city"}
}

// OptionalCityOrErr returns the OptionalCity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) OptionalCityOrErr() (*City, error) {
	if e.loadedTypes[1] {
		if e.OptionalCity == nil {
			// The edge optional_city was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: city.Label}
		}
		return e.OptionalCity, nil
	}
	return nil, &NotLoadedError{edge: "optional_city"}
}

// FriendListOrErr returns the FriendList value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FriendListOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.FriendList, nil
	}
	return nil, &NotLoadedError{edge: "friend_list"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldOptionalNullableBool:
			values[i] = new(sql.NullBool)
		case user.FieldFirstName, user.FieldLastName, user.FieldUserName:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID:
			values[i] = new(uuid.UUID)
		case user.ForeignKeys[0]: // user_required_city
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case user.ForeignKeys[1]: // user_optional_city
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type User", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				u.ID = *value
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				u.UpdatedAt = value.Time
			}
		case user.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				u.FirstName = value.String
			}
		case user.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				u.LastName = value.String
			}
		case user.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				u.UserName = value.String
			}
		case user.FieldOptionalNullableBool:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field optional_nullable_bool", values[i])
			} else if value.Valid {
				u.OptionalNullableBool = new(bool)
				*u.OptionalNullableBool = value.Bool
			}
		case user.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_required_city", values[i])
			} else if value.Valid {
				u.user_required_city = new(uuid.UUID)
				*u.user_required_city = *value.S.(*uuid.UUID)
			}
		case user.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_optional_city", values[i])
			} else if value.Valid {
				u.user_optional_city = new(uuid.UUID)
				*u.user_optional_city = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// QueryRequiredCity queries the "required_city" edge of the User entity.
func (u *User) QueryRequiredCity() *CityQuery {
	return (&UserClient{config: u.config}).QueryRequiredCity(u)
}

// QueryOptionalCity queries the "optional_city" edge of the User entity.
func (u *User) QueryOptionalCity() *CityQuery {
	return (&UserClient{config: u.config}).QueryOptionalCity(u)
}

// QueryFriendList queries the "friend_list" edge of the User entity.
func (u *User) QueryFriendList() *UserQuery {
	return (&UserClient{config: u.config}).QueryFriendList(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return (&UserClient{config: u.config}).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v", u.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(u.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", first_name=")
	builder.WriteString(u.FirstName)
	builder.WriteString(", last_name=")
	builder.WriteString(u.LastName)
	builder.WriteString(", user_name=")
	builder.WriteString(u.UserName)
	if v := u.OptionalNullableBool; v != nil {
		builder.WriteString(", optional_nullable_bool=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User

func (u Users) config(cfg config) {
	for _i := range u {
		u[_i].config = cfg
	}
}
