// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Test implements test operation.
//
// GET /test
func (UnimplementedHandler) Test(ctx context.Context) (r *SchemaA, _ error) {
	return r, ht.ErrNotImplemented
}
