// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Keyboard is the predicate function for keyboard builders.
type Keyboard func(*sql.Selector)

// KeycapModel is the predicate function for keycapmodel builders.
type KeycapModel func(*sql.Selector)

// SwitchModel is the predicate function for switchmodel builders.
type SwitchModel func(*sql.Selector)
